media: 
  input: public
  output: /
content:
  - name: journey
    label: Journey
    type: collection
    path: src/content/journey
    fields:
      - { name: sortOrder, label: Sort Order, type: number }
      - { name: date, label: Date, type: string }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text }